### PR TITLE
travis: Cache only ~/.cargo directory

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by philipc** [comment]
I have merged this yet because the tarpaulin stuff is wrong (it needs to reinstall tarpaulin every time because it depends on nightly), but I don't have time to look into it properly yet.

**Comment by philipc** [comment]
Since we need to reinstall tarpaulin every time, there's no point doing it in before_cache. So drop your last commit (8663660b72ac3eabcdcb05b64ed934ad157b1e4b), and add -f to the install to force a reinstall.

**Comment by lzutao** [comment]
Hm, I think we could use the cargo-outdated crate to check whenever
tarpaulin is outdated and to reinstall it in that case. That will reduce CI
time because of tarpaulin doesn't need to install everytime.

**Comment by philipc** [comment]
cargo-outdated won't help because tarpaulin isn't a dependency, and also it's tarpaulin's dependencies that we need to check, one of which is procmacro2 from the nightly compiler.

**Pull request merged**
