### PR TITLE
write/elf: mark .data.rel.ro as SHF_WRITE

### PR DESCRIPTION
**Pull request by bjorn3**
See https://github.com/bjorn3/rustc_codegen_cranelift/issues/921 for more context.

### CODE REVIEW

**Comment by bjorn3** [comment]
Is there anything you still want to change before the next release?

**Comment by philipc** [comment]
Replacing goblin has been a major change, so I wanted to do more validation of that, but I don't currently have much time.  Did you test cg_clif with both ELF and Mach-O?

**Comment by bjorn3** [comment]
I have somewhat tested it with ELF. (not the full cg_clif test suite though) I haven't tested with Mach-O. I think I will create a draft PR for cg_clif tomorrow, so I can test it on CI.

**Comment by bjorn3** [comment]
Both ELF and Mach-O work fine for cg_clif on CI: https://github.com/bjorn3/rustc_codegen_cranelift/runs/509535100

**Comment by philipc** [comment]
Great, thanks for testing. I'll try to do some sanity checks for a couple of other users of this crate, and do a release this week.

**Comment by philipc** [comment]
0.18.0 is released.

**Pull request merged**
