### PR TITLE
Print error when --all-features is used

### LINKED ISSUE #232: Rustc integration setup
The current rustc integration setup is strictly speaking not conforming with the cargo rule, that [features are additive](https://github.com/rust-lang/cargo/issues/4328). LSP implementations like rust-analyzer assume that crates strictly adhere to that rule and compile/check with `--all-features` by default, which breaks because of the `rustc-dep-of-std` feature. This causes issues like https://github.com/rust-analyzer/rust-analyzer/issues/4702.

I can't think of an elegant solution for this problem, but maybe something along the lines of [explicitly failing](https://internals.rust-lang.org/t/mutually-exclusive-feature-flags/8601/2) with `compile_error!` and a helpful message would make this more discoverable.

### PR DESCRIPTION
**Pull request by philipc**
Fixes #232

### CODE REVIEW

**Comment by matprec** [comment]
This error is swamped among 1428 other errors, as the rest of the code still is type checked. For this to be visible, all modules would need to be `#[cfg(not(feature = cargo-all))]` in some way

**Comment by matprec** [comment]
Maybe something like this to reduce noise:

```rust
pub use modules::*;
#[cfg(not(feature = cargo-all))]
mod modules {
     pub mod foo;
     mod bar;
}
```

**Comment by philipc** [comment]
It's the first error. I'm not keen on adding further workarounds for this. rust-analyzer is disabling that setting anyway.

**Comment by matprec** [comment]
Fair enogh :) Looks good to me

**Pull request merged**
